# Generated by Django 5.0 on 2023-12-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='atalaiashouse',
            fields=[
                ('codClients', models.AutoField(default='1900-01-01', primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamento', models.CharField(choices=[('0', 'Dinheiro'), ('1', 'Pix'), ('2', 'Crédito'), ('3', 'Dédito')], max_length=15, verbose_name='Forma de Pagamento')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(choices=[('0', 'Pão Francês'), ('1', 'Pão de Hamburguer'), ('2', 'Baguete de Peito de Peru'), ('3', 'Baguete de Frango'), ('4', 'Coxinha (cento)'), ('5', 'Kibe (cento)'), ('6', 'Empada de Frango (cento)'), ('7', 'Bolo de Festa - Chocolate'), ('8', 'Bolo de Festa - Morango'), ('9', 'Bolo de Festa - Abacaxi'), ('10', 'Bolo de Festa - Pelado')], max_length=30, verbose_name='Encomendar')),
                ('qtd', models.IntegerField(verbose_name='Quantidade')),
                ('dtentrega', models.DateTimeField(verbose_name='Data de Entrega')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('numero', models.IntegerField(verbose_name='DDD Número')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('cfp', models.CharField(max_length=16, verbose_name='CPF')),
            ],
        ),
    ]
